Coordinate_xml_path: Configuration\pixel_coordinates.xml

Default:
    min_overlap_thres: 0.02
    max_overlap_thres: 0.40
    overflow_thres: 0.5

Special_spot:
    b7:
        overflow_thres: 0.8
    d3:
        max_overlap_thres : .60
        
Parked_spots:
    a1
    a4
    a6
    b4
    c6
        